version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: mbur17/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - ./backend/media:/app/media
    depends_on:
      - db

  frontend:
    image: mbur17/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: mbur17/foodgram_gateway
    env_file: .env
    ports:
      - 8888:80
    volumes:
      - static:/staticfiles/
      - ./backend/media:/app/media
