# int
COOKING_MAX_TIME = 720
COOKING_MIN_TIME = 1
INGREDIENT_MAX_LENGTH = 128
INGREDIENT_MAX_AMOUNT = 10000
INGREDIENT_MIN_AMOUNT = 1
RECIPE_MAX_LENGTH = 256
TAG_MAX_LENGTH = 32
UNIT_MAX_LENGTH = 64

# str
RECIPE_IMAGE_DIR = 'recipes/images/'
